from main.CourseRegistrationSimulation import CourseRegistrationSimulation
from main.CourseRegistrationSystem import CourseRegistrationSystem
from databaseController.CourseDBController import CourseDBController


courseRegistrationSystem = CourseRegistrationSystem(courseDBController= CourseDBController())
CLI = CourseRegistrationSimulation(courseRegistrationSystem)
CLI.run()