from CourseRegistrationSimulation import CourseRegistrationSimulation
from CourseRegistrationSystem import CourseRegistrationSystem
from databaseController.CourseDBController import CourseDBController


courseRegistrationSystem = CourseRegistrationSystem(courseDBController= CourseDBController())
CLI = CourseRegistrationSimulation(courseRegistrationSystem)
CLI.run()